//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoRatChat.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwoRatChat.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply (reload) skin:.
        /// </summary>
        public static string BUT_ApplySkin {
            get {
                return ResourceManager.GetString("BUT_ApplySkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add chat source....
        /// </summary>
        public static string cxt_AddChatSource {
            get {
                return ResourceManager.GetString("cxt_AddChatSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show blacklist editor....
        /// </summary>
        public static string cxt_Blacklist {
            get {
                return ResourceManager.GetString("cxt_Blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string cxt_CancelMenu {
            get {
                return ResourceManager.GetString("cxt_CancelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close TwoRatChat.
        /// </summary>
        public static string cxt_Close {
            get {
                return ResourceManager.GetString("cxt_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close chat source.
        /// </summary>
        public static string cxt_CloseChat {
            get {
                return ResourceManager.GetString("cxt_CloseChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Command editor....
        /// </summary>
        public static string cxt_CommandEditor {
            get {
                return ResourceManager.GetString("cxt_CommandEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на База данных зрителей....
        /// </summary>
        public static string cxt_CustomUsers {
            get {
                return ResourceManager.GetString("cxt_CustomUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show fortune ring editor....
        /// </summary>
        public static string cxt_Fortunering {
            get {
                return ResourceManager.GetString("cxt_Fortunering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show options....
        /// </summary>
        public static string cxt_Options {
            get {
                return ResourceManager.GetString("cxt_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show poll editor....
        /// </summary>
        public static string cxt_Polleditor {
            get {
                return ResourceManager.GetString("cxt_Polleditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reload chat.
        /// </summary>
        public static string cxt_ReloadChat {
            get {
                return ResourceManager.GetString("cxt_ReloadChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset chat window position.
        /// </summary>
        public static string cxt_ResetPosition {
            get {
                return ResourceManager.GetString("cxt_ResetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open skin designer....
        /// </summary>
        public static string cxt_SkinDesigner {
            get {
                return ResourceManager.GetString("cxt_SkinDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string dbt_cancel {
            get {
                return ResourceManager.GetString("dbt_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string dbt_ok {
            get {
                return ResourceManager.GetString("dbt_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat source:.
        /// </summary>
        public static string dtb_ChatSource {
            get {
                return ResourceManager.GetString("dtb_ChatSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error 001: Channel not found..
        /// </summary>
        public static string ERROR_001 {
            get {
                return ResourceManager.GetString("ERROR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error 002: Site API was changed..
        /// </summary>
        public static string ERROR_002 {
            get {
                return ResourceManager.GetString("ERROR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли и логины хранятся с минимальным шифрованием на жестком диске (в файле настройки). Хранить их тут небезопасно!.
        /// </summary>
        public static string MES_BotWarning {
            get {
                return ResourceManager.GetString("MES_BotWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stream channel or ID:.
        /// </summary>
        public static string MES_ChannelOrID {
            get {
                return ResourceManager.GetString("MES_ChannelOrID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Message deleted&gt;.
        /// </summary>
        public static string MES_Deleted {
            get {
                return ResourceManager.GetString("MES_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fatal error, please restart program..
        /// </summary>
        public static string MES_FatalError {
            get {
                return ResourceManager.GetString("MES_FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow GG animated smiles (reload required):.
        /// </summary>
        public static string MES_GGAllowAnimated {
            get {
                return ResourceManager.GetString("MES_GGAllowAnimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow GG premium smiles (reload required):.
        /// </summary>
        public static string MES_GGAllowChannel {
            get {
                return ResourceManager.GetString("MES_GGAllowChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable server.
        /// </summary>
        public static string MES_HttpEnable {
            get {
                return ResourceManager.GetString("MES_HttpEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Http listen uri (reload required):.
        /// </summary>
        public static string MES_HttpListen {
            get {
                return ResourceManager.GetString("MES_HttpListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Youtube Channel ID:.
        /// </summary>
        public static string MES_Id {
            get {
                return ResourceManager.GetString("MES_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat label:.
        /// </summary>
        public static string MES_Label {
            get {
                return ResourceManager.GetString("MES_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TwoRatChat options..
        /// </summary>
        public static string MES_Options {
            get {
                return ResourceManager.GetString("MES_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Streamer nick:.
        /// </summary>
        public static string MES_Streamer {
            get {
                return ResourceManager.GetString("MES_Streamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Streamer nick or ID:.
        /// </summary>
        public static string MES_StreamerOrID {
            get {
                return ResourceManager.GetString("MES_StreamerOrID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Streamer ID:.
        /// </summary>
        public static string MES_StrId {
            get {
                return ResourceManager.GetString("MES_StrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WARNING! Do not change this urls by yourself. After changes reboot required!.
        /// </summary>
        public static string MES_UrlWarning {
            get {
                return ResourceManager.GetString("MES_UrlWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} стал новым фолловером!.
        /// </summary>
        public static string NewFollowerMessage {
            get {
                return ResourceManager.GetString("NewFollowerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accent color:.
        /// </summary>
        public static string OPT_AccentColor {
            get {
                return ResourceManager.GetString("OPT_AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow hitbox colors (only new messages):.
        /// </summary>
        public static string OPT_AllowHitboxColors {
            get {
                return ResourceManager.GetString("OPT_AllowHitboxColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow leveling (only new messages):.
        /// </summary>
        public static string OPT_AllowLeveling {
            get {
                return ResourceManager.GetString("OPT_AllowLeveling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Background color:.
        /// </summary>
        public static string OPT_BackColor {
            get {
                return ResourceManager.GetString("OPT_BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show border:.
        /// </summary>
        public static string OPT_Border {
            get {
                return ResourceManager.GetString("OPT_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow check twitch followers:.
        /// </summary>
        public static string OPT_CheckFollowers {
            get {
                return ResourceManager.GetString("OPT_CheckFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable full window dragging:.
        /// </summary>
        public static string OPT_DisableFullDrag {
            get {
                return ResourceManager.GetString("OPT_DisableFullDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download history:.
        /// </summary>
        public static string OPT_DowloadHistory {
            get {
                return ResourceManager.GetString("OPT_DowloadHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show &quot;new follower&quot; message in chat:.
        /// </summary>
        public static string OPT_FollowersInChat {
            get {
                return ResourceManager.GetString("OPT_FollowersInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Goodgame header mode:.
        /// </summary>
        public static string OPT_GGHeaderMode {
            get {
                return ResourceManager.GetString("OPT_GGHeaderMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save chat as image (*.png):.
        /// </summary>
        public static string OPT_ImagePath {
            get {
                return ResourceManager.GetString("OPT_ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max image size:.
        /// </summary>
        public static string OPT_MaxImageSize {
            get {
                return ResourceManager.GetString("OPT_MaxImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is window mouse transparent:.
        /// </summary>
        public static string OPT_MouseTransparent {
            get {
                return ResourceManager.GetString("OPT_MouseTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable overlay mode (reload required):.
        /// </summary>
        public static string OPT_OverlayMode {
            get {
                return ResourceManager.GetString("OPT_OverlayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Sometime OBS or XSplit require to this option).
        /// </summary>
        public static string OPT_OverlayMode2 {
            get {
                return ResourceManager.GetString("OPT_OverlayMode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activate command on first message:.
        /// </summary>
        public static string OPT_PlaySoundOnFirstMessage {
            get {
                return ResourceManager.GetString("OPT_PlaySoundOnFirstMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show images from:.
        /// </summary>
        public static string OPT_ShowImagesFrom {
            get {
                return ResourceManager.GetString("OPT_ShowImagesFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show button in taskbar (EXPERIMENTAL):.
        /// </summary>
        public static string OPT_ShowInTaskbar {
            get {
                return ResourceManager.GetString("OPT_ShowInTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show twitch subscriber icon (reload required):.
        /// </summary>
        public static string OPT_ShowTwitchSubsIcon {
            get {
                return ResourceManager.GetString("OPT_ShowTwitchSubsIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show images from urls:.
        /// </summary>
        public static string OPT_ShowUrlsAsImages {
            get {
                return ResourceManager.GetString("OPT_ShowUrlsAsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat root html (skin):.
        /// </summary>
        public static string OPT_Skin {
            get {
                return ResourceManager.GetString("OPT_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Always on top:.
        /// </summary>
        public static string OPT_TopMost {
            get {
                return ResourceManager.GetString("OPT_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom Twitch API KEY:.
        /// </summary>
        public static string OPT_TwitchAPIKey {
            get {
                return ResourceManager.GetString("OPT_TwitchAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow twitch colors (only new messages):.
        /// </summary>
        public static string OPT_UseColors {
            get {
                return ResourceManager.GetString("OPT_UseColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст с вопросом:.
        /// </summary>
        public static string OPT_voice_ask {
            get {
                return ResourceManager.GetString("OPT_voice_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восклицание:.
        /// </summary>
        public static string OPT_voice_caps {
            get {
                return ResourceManager.GetString("OPT_voice_caps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voice on first message (clear to silence):.
        /// </summary>
        public static string OPT_voice_FirstMeet {
            get {
                return ResourceManager.GetString("OPT_voice_FirstMeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voice on follower (clear to silence):.
        /// </summary>
        public static string OPT_voice_Followers {
            get {
                return ResourceManager.GetString("OPT_voice_Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom voice for viewers (require restart):.
        /// </summary>
        public static string OPT_voice_Personals {
            get {
                return ResourceManager.GetString("OPT_voice_Personals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voice on promoute message (clear to silence):.
        /// </summary>
        public static string OPT_voice_Promoute {
            get {
                return ResourceManager.GetString("OPT_voice_Promoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обычный текст:.
        /// </summary>
        public static string OPT_voice_talk {
            get {
                return ResourceManager.GetString("OPT_voice_talk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom Youtube API KEY:.
        /// </summary>
        public static string OPT_YoutubeAPIKey {
            get {
                return ResourceManager.GetString("OPT_YoutubeAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show youtube user icon:.
        /// </summary>
        public static string OPT_YoutubeIcon {
            get {
                return ResourceManager.GetString("OPT_YoutubeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string TAB_About {
            get {
                return ResourceManager.GetString("TAB_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Awards.
        /// </summary>
        public static string TAB_Awards {
            get {
                return ResourceManager.GetString("TAB_Awards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot.
        /// </summary>
        public static string TAB_Bot {
            get {
                return ResourceManager.GetString("TAB_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main.
        /// </summary>
        public static string TAB_Main {
            get {
                return ResourceManager.GetString("TAB_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat urls.
        /// </summary>
        public static string TAB_Urls {
            get {
                return ResourceManager.GetString("TAB_Urls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voice.
        /// </summary>
        public static string TAB_Voice {
            get {
                return ResourceManager.GetString("TAB_Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. Enter here &apos;pick phrase&apos; to select brave from chat..
        /// </summary>
        public static string tip_FRPhrase {
            get {
                return ResourceManager.GetString("tip_FRPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3. Seconds before select..
        /// </summary>
        public static string tip_FRSeconds {
            get {
                return ResourceManager.GetString("tip_FRSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2. Winners count (default 1)..
        /// </summary>
        public static string tip_FRWinners {
            get {
                return ResourceManager.GetString("tip_FRWinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во зрителей/кол-во людей в чате/Позиция среди стримов (меньше - лучше).
        /// </summary>
        public static string tip_goodGameTooltip {
            get {
                return ResourceManager.GetString("tip_goodGameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow user change choice:.
        /// </summary>
        public static string tip_PollAllowChange {
            get {
                return ResourceManager.GetString("tip_PollAllowChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow user remove choice:.
        /// </summary>
        public static string tip_PollAllowRemove {
            get {
                return ResourceManager.GetString("tip_PollAllowRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to TwoRatChat.
        ///Please, press the right mouse button to add chat source..
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
